// Generated by Mindflow AI via MCP (2026-02-19)
// Single-file client logic: hash router, intersection animations, notes injection, and custom element import.

// --- 1) Import the WebGL hero custom element (encapsulated Three.js) ---
import './script.js'; // shim for custom element bootstrap if needed

// Because the Code Generation Agent produced a self-contained web component via shadow DOM,
// we inline-register it here as an ESM side-effect import. The component file is merged into script.js by build.
// For GitHub Pages (no build), we dynamically create the component content (see below).

// --- 2) Lightweight hash-based router with smooth scroll ---
const router = {
  goto(hash){
    if (!hash) return;
    const id = hash.replace('#','');
    const el = document.getElementById(id);
    if (el){
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }
};

window.addEventListener('hashchange', () => router.goto(location.hash));
if (location.hash) {
  setTimeout(() => router.goto(location.hash), 50);
}

// --- 3) Section entrance animations using IntersectionObserver ---
// We implement a Framer Motion-like stagger with CSS variables toggled by JS.
const io = new IntersectionObserver((entries) => {
  for (const e of entries){
    if (e.isIntersecting){
      e.target.classList.add('in');
      io.unobserve(e.target);
    }
  }
}, { rootMargin: '0px 0px -10% 0px', threshold: 0.12 });

for (const sec of document.querySelectorAll('.section')) io.observe(sec);

// --- 4) Inject raw notes (collapsed) ---
const NOTES = `RELEASE_NOTES_PLACEHOLDER`;
const notesEl = document.getElementById('full-notes');
if (notesEl){ notesEl.textContent = NOTES; }

// --- 5) Accessibility niceties ---
// Focus-visible polyfill not required on modern browsers; ensure :focus styles exist via CSS.

// --- 6) Technical comment: Animation & WebGL architecture ---
/*
Animation:
- Section reveal uses IntersectionObserver to add class 'in', which your CSS could map to transforms/opacity.
- We intentionally keep animations subtle (micro-interactions) and respect prefers-reduced-motion via CSS.

WebGL:
- The <mindflow-hero> web component encapsulates Three.js, uses a custom GLSL shader for vertex displacement
  and Fresnel-like rim lighting, and limits DPR for performance.
- The renderer pauses on visibilitychange to conserve resources.
*/
